name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: TypeScript type checking
        working-directory: frontend
        run: npx tsc --noEmit

      - name: Lint
        working-directory: frontend
        run: npm run lint

      - name: Run tests
        working-directory: frontend
        run: npm test -- --watchAll=false --coverage --maxWorkers=2 --verbose

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::218141621131:role/github-actions
          aws-region: us-east-1

      - name: Get Cognito Values
        id: get-cognito
        run: |
          USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 1 --query 'UserPools[0].Id' --output text)
          CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id $USER_POOL_ID --max-results 1 --query 'UserPoolClients[0].ClientId' --output text)
          echo "user_pool_id=$USER_POOL_ID" >> $GITHUB_OUTPUT
          echo "client_id=$CLIENT_ID" >> $GITHUB_OUTPUT

      - name: Build Next.js site
        working-directory: frontend
        env:
          NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${{ steps.get-cognito.outputs.user_pool_id }}
          NEXT_PUBLIC_COGNITO_CLIENT_ID: ${{ steps.get-cognito.outputs.client_id }}
        run: npm run build

      - name: Sync to S3
        run: |
          aws s3 sync frontend/out/ s3://amianai.com --delete --cache-control "max-age=86400"

      - name: Invalidate CloudFront
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?contains(@, 'amianai.com')]].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
